---
# tasks file for ansible-postfix
- name: Checking to make sure postfix is installed
  apt: name={{ item }} state=installed
  when: ansible_os_family == 'Debian'
  tags: [postfix]
  with_items:
    - postfix
    - mailutils

- name: Create postfix configurations
  template: src={{ item }}.j2 dest={{ postfix_conf_dir }}/{{ item }} mode=0644 owner=root group=root backup=yes
  notify: restart postfix
  tags: [postfix]
  register: postfix
  with_items:
    - generic
    - main.cf

- name: Checking to make sure postfix is running
  service: name=postfix state=running enabled=yes
  tags: [postfix]

- name: rebuilding generic.db
  command: postmap /etc/postfix/generic
  tags: [postfix]
  when: postfix.changed
